---
abstract: 'XS implementation of URL::Encode'
author:
  - 'Christian Hansen, <chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.59'
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: URL-Encode-XS
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Exporter: 0
  URL::Encode: '0.03'
  XSLoader: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chansen/p5-url-encode-xs
version: '0.03'
